json.id product.id
json.name product.name
json.price product.price
json.images product.images
json.description product.description
json.price_discount product.is_discounted?
json.sales_tax product.tax
json.sales_total product.total
json.supplier product.supplier
